# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-11 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0015_auto_20190921_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReunionConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('server', models.CharField(max_length=128, verbose_name='DB server')),
                ('username', models.CharField(max_length=128, verbose_name='DB user')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='DB server')),
                ('users', models.ManyToManyField(blank=True, related_name='_reunionconnector_users_+', related_query_name='+', to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'Connecteur de test r\xe9union',
            },
        ),
    ]
